FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /build
COPY . .

RUN dotnet tool restore
RUN dotnet paket restore
RUN dotnet build ExtractorLauncher/

ARG VERSION_ARGS

RUN dotnet publish -c Release -o /build/deploy "$VERSION_ARGS" ExtractorLauncher/
