FROM eu.gcr.io/cognitedata/dotnet-mono:3.0-sdk

WORKDIR /build
COPY . .

RUN mono .paket/paket.exe restore
RUN dotnet build ExtractorLauncher/

RUN dotnet publish -c Release -o /build/deploy /p:PublishTrimmed="false" ExtractorLauncher
