FROM mcr.microsoft.com/dotnet/sdk:5.0

WORKDIR /build
COPY . .

RUN dotnet tool restore
RUN dotnet paket restore
RUN dotnet build

RUN dotnet publish -c Release -o /build/deploy /p:PublishTrimmed="false"
