FROM mcr.microsoft.com/dotnet/runtime:10.0
VOLUME /config
VOLUME /logs
COPY /deploy /bridge
WORKDIR /bridge

# Update distro packages
RUN apt-get -qq update \
    && apt-get -qq upgrade \
    && apt-get -qq clean \
    && rm -rf /var/lib/apt/lists/*

ENV MQTT_BRIDGE_CONFIG_DIR="/config"

RUN mkdir -p /logs
RUN chmod -R a+rw /logs

RUN groupadd -g 1001 extractor && useradd -m -u 1001 -g extractor extractor
USER extractor

ENTRYPOINT ["dotnet", "/bridge/MQTTCDFBridge.dll"]
