FROM mcr.microsoft.com/dotnet/runtime:8.0
VOLUME /config
VOLUME /logs
COPY /deploy /bridge
WORKDIR /bridge

ENV MQTT_BRIDGE_CONFIG_DIR="/config"

RUN mkdir -p /logs
RUN chmod -R a+rw /logs

RUN groupadd -g 1000 extractor && useradd -m -u 1000 -g extractor extractor
USER extractor

ENTRYPOINT ["dotnet", "/bridge/MQTTCDFBridge.dll"]
