# This is a minimal configuration for remote configuration of the extractor. 
# A full configuration file needs to be added to the extraction pipeline in addition to using this file locally.

type: remote

version: 2

cognite:
    # The project to connect to in the API, uses the environment variable COGNITE_PROJECT.
    project: "${COGNITE_PROJECT}"    
    # Cognite base url
    host: "${COGNITE_BASE_URL}"
    # See the example config for the full list of options.
    idp-authentication:
        # URL to fetch tokens from. Either this or tenant must be present.
        token-url: ${COGNITE_TOKEN_URL}
        # Application Id
        client-id: ${COGNITE_CLIENT_ID}
        # Client secret
        secret: ${COGNITE_CLIENT_SECRET}
        # List of resource scopes, ex:
        # scopes:
        #   - scopeA
        #   - scopeB
        scopes:
          - ${COGNITE_SCOPE}

        audience: ${COGNITE_AUDIENCE}
        # Which implementation to use in the authenticator. One of
        # MSAL (recommended) - Microsoft Authentication Library, works only with authority/tenant
        # Basic - Post to authentication endpoint and parse JSON response, works with both authority/tenant and token-url
        # Default is MSAL
        implementation: Basic

    extraction-pipeline:
        external-id: ${COGNITE_EXTRACTION_PIPELINE}
