# Template for the config file,
# Defaults to config.bridge.yml in ./config. The first argument supplied to the program can also be the path to a config file
# The values here are generally the default values, except for the contents of lists etc.
# Your config file can contain only a subset of these config options. Any extra options will
# cause the bridge to fail.

mqtt:
    # TCP Broker URL
    host:
    # TCP Broker port
    port:
    # MQTT broker username
    username:
    # MQTT broker password
    password:
    # True to enable TLS
    use-tls:
    # Mqtt client id. Should be unique for a given broker.
    client-id: cognite-cdf-bridge
    # Data set to use for new objects. Existing objects will not be updated
    data-set-id:
    # Assets topic
    asset-topic: cognite/opcua/assets
    # Timeseries topic
    ts-topic: cognite/opcua/timeseries
    # Events topic
    event-topic: cognite/opcua/events
    # Datapoints topic
    datapoint-topic: cognite/opcua/datapoints

cognite:
    # The project to connect to in the API
    project:
    # Cognite api key
    api-key:
    # Cognite service url
    host: "https://api.cognitedata.com"

logging:
    # Log levels: 'verbose', 'debug', 'information', 'warning', 'error', 'fatal'.
    # Writes log events at this level to the Console. 
    # If not present, or if the level is invalid, Console is not used. 
    console-level: information
    # Writes log events at this level to a file. Logs will roll over to new files daily.
    # If not present, or if the level is invalid, logging to file is disabled.
    file-level:
    # Folder for logging output. If not present, logging to file is disabled.
    log-folder:
    # Maximum number of logs files that are kept in the log folder.
    retention-limit: 31
    # File containing the credentials used for authentication with GCP.
    # If present, sends log events Stackdriver.
    # Events at all levels are sent.
    stackdriver-credentials:
    # Name to be assigned to the Stackdriver log.
    stackdriver-log-name: