# Template for the config file,
# Defaults to config.bridge.yml in ./config. The first argument supplied to the program can also be the path to a config file
# The values here are generally the default values, except for the contents of lists etc.
# Your config file can contain only a subset of these config options. Any extra options will
# cause the bridge to fail.

# Version of the config file, if breaking changes are introduced to config, this number must be updated along with the config file.
# Must be included in the config file.
version: 1

mqtt:
    # TCP Broker URL
    host:
    # TCP Broker port
    port:
    # MQTT broker username
    username:
    # MQTT broker password
    password:
    # True to enable TLS
    use-tls:
    # Mqtt client id. Should be unique for a given broker.
    client-id: cognite-cdf-bridge
    # Assets topic
    asset-topic: cognite/opcua/assets
    # Timeseries topic
    ts-topic: cognite/opcua/timeseries
    # Events topic
    event-topic: cognite/opcua/events
    # Datapoints topic
    datapoint-topic: cognite/opcua/datapoints

cognite:
    # The project to connect to in the API
    project:
    # Cognite api key
    api-key:
    # Cognite service url
    host: "https://api.cognitedata.com"
    # Config for authentication if a bearer access token has to be used for authentication.
    # Leave empty to disable.
    idp-authentication:
        # Application Id
        client-id:
        # Directory tenant
        tenant:
        # Client secret
        secret:
        # Resource scope
        scope:
        # Minimum time-to-live in seconds for the token (optional)
        min-ttl: 30
    # Configure automatic retries on requests to CDF. Can be left out to keep default values.
    cdf-retries:
        # Timeout in ms for each individual try
        timeout: 80000
        # Maximum number of retries, less than 0 retries forever
        max-retries: 5
        # Max delay in ms between each try. Base delay is calculated according to 125*2^retry ms.
        # If less than 0, there is no maximum. (0 means that there is never any delay)
        max-delay: 5000
    # Configure chunking of data on requests to CDF. Note that increasing these may cause requests to fail due to limits in CDF.
    cdf-chunking:
        # Maximum number of timeseries per get/create timeseries request
        time-series: 1000
        # Maximum number of assets per get/create asset request
        assets: 1000
        # Maximum number of timeseries per datapoint create request
        data-point-time-series: 10000
        # Maximum number of datapoints per datapoint create request
        data-points: 100000
        # Maximum number of events per get/create events request
        events: 1000
    # Configure how requests to CDF should be throttled
    cdf-throttling:
        # Maximum number of parallel requests per timeseries operation
        time-series: 20
        # Maximum number of parallel requests per assets operation
        assets: 20
        # Maximum number of parallel requests per datapoints operation
        data-points: 10
        # Maximum number of parallel requests per raw operation
        raw: 10
        # Maximum number of parallel requests per get first/last datapoint operation
        ranges: 20
        # Maximum number of parallel requests per events operation
        events: 20
    # Configure if the SDK should do logging of requests
    sdk-logging:
        # True to disable logging from the SDK
        disable: false
        # Level of logging, one of fatal, error, warning, information|, debug, verbose.
        level: debug
        # Format of the log message
        format: "CDF ({Message}): {HttpMethod} {Url} - {Elapsed} ms"

logger:
    # Writes log events at this level to the Console. One of verbose, debug, information, warning, error, fatal.
    # If not present, or if the level is invalid, Console is not used.
    console:
        level:
    # Writes log events at this level to a file. Logs will roll over to new files daily.
    # If not present, or if the level is invalid, logging to file is disabled.
    file:
        level:
        # Path for logging output. If not present, logging to file is disabled.
        path: # "logs/log.txt"
        # Maximum number of logs files that are kept in the log folder.
        retention-limit: 31
        # Rolling interval for log files. Either "day" or "hour".
        rolling-interval: "day"