# Template for the config file,
# Defaults to config.yml in ./config.

MQTT:
    # TCP Broker URL
    Host:
    # TCP Broker port
    Port:
    # MQTT broker username
    Username:
    # MQTT broker password
    Password:
    # True to enable TLS
    UseTls:
    # Mqtt client id. Should be unique for a given broker.
    ClientId: cognite-cdf-bridge
    # Assets topic
    AssetTopic: cognite/opcua/assets
    # Timeseries topic
    TSTopic: cognite/opcua/timeseries
    # Events topic
    EventTopic: cognite/opcua/events
    # Datapoints topic
    DatapointTopic: cognite/opcua/datapoints

CDF:
    # The project to connect to in the API
    Project:
	# Cognite api key
    ApiKey:
    # Cognite service url
    Host: "https://api.cognitedata.com"

Logging:
    # Log levels: 'verbose', 'debug', 'information', 'warning', 'error', 'fatal'.
    # Writes log events at this level to the Console. 
    # If not present, or if the level is invalid, Console is not used. 
    ConsoleLevel: information
    # Writes log events at this level to a file. Logs will roll over to new files daily.
    # If not present, or if the level is invalid, logging to file is disabled.
    FileLevel:
    # Folder for logging output. If not present, logging to file is disabled.
    LogFolder:
    # Maximum number of logs files that are kept in the log folder.
    RetentionLimit: 31
    # File containing the credentials used for authentication with GCP.
    # If present, sends log events Stackdriver.
    # Events at all levels are sent.
    StackdriverCredentials:
    # Name to be assigned to the Stackdriver log.
    StackdriverLogName: