name: Build and test extractor

on:
    pull_request:
        branches: [ master ]

jobs:
    common:
        uses: ./.github/workflows/common.yml
        secrets: inherit
    test:
        uses: ./.github/workflows/test.yml
        secrets: inherit
    build:
        runs-on: ubuntu-latest
        needs:
            - test
        steps:
          - run: echo "Yep, this sure is built"
    verify-schema:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4
        - name: Install python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'

        - name: Install extractor uploader
          env: 
            PYPI_ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_READONLY_TOKEN_USER_PUBLIC_REPOS }}
            PYPI_ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_READONLY_TOKEN_PUBLIC_REPOS }}
          run: |
            python -m pip install --upgrade pip
            pip install cognite-extractor-publisher --extra-index-url "https://${PYPI_ARTIFACTORY_USERNAME}:${PYPI_ARTIFACTORY_PASSWORD}@cognite.jfrog.io/cognite/api/pypi/snakepit/simple"
  
        - name: Verify manifest
          run: |
            publish-extractor validate --manifest manifest.yml --config-files Test/config.test.yml